use_frameworks!

target 'WeakCollection_Example' do
  platform :ios, '10.0'
  pod 'WeakCollection', :path => '../'
  target 'WeakCollection_Tests' do
    platform :ios, '10.0'
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.1'
    pod 'iOSSnapshotTestCase' , '~> 6.0.0'
    pod 'Nimble-Snapshots' , '~> 7.0.0'
  end
end


